name: Bug report
description: Create a report to help us improve
title: '[Bug]: '
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system do you use? Please provide the version as well."
      placeholder: "Android 13"
    validations:
      required: true  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: ""
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: additional
    attributes:
      label: Relevant log output
      description: Add any other context about the problem here.
      render: shell

